export const GET_USERS_DATA = "GET_USERS_DATA"

export const ADD_USERS_DATA = "ADD_USERS_DATA"

export const DELETE_USERS_DATA = "DELETE_USERS_DATA"

export const UPDATE_USERS_DATA = "UPDATE_USERS_DATA"

export const USERS_DATA_PENDIND = "DELETE_USERS_DATA_PENDIND"
export const USERS_DATA_SUCCESS = "DELETE_USERS_DATA_SUCCESS"
export const USERS_DATA_FAILURE = "DELETE_USERS_DATA_FAILURE"
